baseURL = 'https://waiyan13.github.io/'
languageCode = 'en-us'
title = 'Midnight Essays'
theme = 'archie'

[params]
  mode = 'dark'
  useCDN = 'true'

[[params.social]]
  name = "GitHub"
  icon = "github"
  url = "https://github.com/waiyan13"
